# use for API testing via Visual Studio Code with the REST Client extension

@host = http://127.0.0.1:8000
@api_key = f1234
@donatello_key = f1111
@user_key = 52d838da-3c1e-45f4-8b93-7a45f4524384

### Generate User Key and send it to mail
POST {{host}}/user/donates
Content-Type: application/json
X-Key: {{donatello_key}}

{
  "pubId": "D41-23",
  "message": "your_mail",
  "amount": "100"
}

### Activate User
POST {{host}}/user/activate
Content-Type: application/json
X-Api-Key: {{api_key}}
X-User-Key: {{user_key}}

### GPT Request
POST {{host}}/
Content-Type: application/json
X-Api-Key: {{api_key}}


X-User-Key: {{user_key}}

{
  "test_type": "Math",
  "question": "What is 2 + 2?",
  "prompt": 1,
  "answers": ["1", "2", "3", "4"]
}



### OlLAMA GPT Request
POST http://127.0.0.1:11434/api/generate
Content-Type: application/json

{
  "model": "llama3",
  "prompt": "What color is the sky at different times of the day?",
  "stream": false
}

